

            <!--数据 -->
            var datas = [
        {
            "aid": "21984",
            "uid": "1512",
            "username": "陈亚超",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "0325 今日关注 15点",
            "from": " ",
            "fromurl": " ",
            "summary": "【马来西亚总理呼吁勿将客机失联事件“政治化”】 中国日报网消息：马来西亚总理纳吉布3月25号在议会发表讲话，呼吁政府官员及反对派勿将马航客机失联事件“政治化”。 纳吉布说：“现在是我们与机上人员表达团结 ...",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201403/25/151750zlkl1kfjf5liz0mk.jpg",
            "dateline": "7 分钟前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201403/25/151754ngffd3xvda3vv88z.mp3",
            "viewnum": 4615,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            },
        {
            "aid": "21981",
            "uid": "1512",
            "username": "陈亚超",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "0325 资讯速览 15点",
            "from": " ",
            "fromurl": " ",
            "summary": "郑州日报消息：北大、清华两所名校自主招生复试时间敲定，都要求通过初试的考生从今天（25号）起上网打印面试准考证和体质测试准考证，复试定于3月29日开始。http://news.dahe.cn/2014/03-25/102701731.html郑州晚报 ...",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145627xtto78ofqkrfczd5.jpg",
            "dateline": "12 分钟前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145631s6l1xhlzzxhvrde3.mp3",
            "viewnum": 3773,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            },
        {
            "aid": "19853",
            "uid": "5",
            "username": "李泉逸",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "亚洲行—上海的城隍庙",
            "from": " ",
            "fromurl": " ",
            "summary": "一起来看看上海的城隍庙是什么样子吧~",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201401/30/110827ck6cccecfjkhy620.jpg",
            "dateline": "13 分钟前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201401/30/110812fqxq9uxuassauqba.mp3",
            "viewnum": 552,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            },
        {
            "aid": "21158",
            "uid": "12",
            "username": "糊糊",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "陈奕迅 - 感情约",
            "from": " ",
            "fromurl": " ",
            "summary": "感情约 专辑:一滴眼泪 作词：姚若龙　作曲：陈美威 无声的夜空是片深深的蓝 想不挽留你才发现洒脱好难 心疼的凝望你眼里星光灿烂 永远不舍得你为难 Mm... 爱过就很美何必说欠与还 为什么离开我不要答案 你说曾真 ...",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201403/04/084426i5245ajp9z7p5i0f.jpg",
            "dateline": "14 分钟前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201403/04/084448x2frcqtv0l6n9vc5.mp3",
            "viewnum": 526,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            },
        {
            "aid": "21982",
            "uid": "1512",
            "username": "陈亚超",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "0325 媒体扫描 14点",
            "from": " ",
            "fromurl": " ",
            "summary": "公务员报考近年来一直是我国备受关注的大事，报考人数居高不下也引发社会上的高度关注。2014年地方公务员考试正陆续进行着，不过今年各地考试报名火爆情况却不如以前。下面我们就来关注一下各地今年公务员报考情况和 ...",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145756doi8wdw9cwz6zixu.jpg",
            "dateline": "半小时前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145800na1wv7tiuuo4qynm.mp3",
            "viewnum": 4325,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            },
        {
            "aid": "21983",
            "uid": "1512",
            "username": "陈亚超",
            "newseditor": " ",
            "newsbeam": " ",
            "title": "0325 今日关注 14点",
            "from": " ",
            "fromurl": " ",
            "summary": "【贫困地区农村学生上重点大学人数将超过30万】 人民网消息：昨天（24号），教育部下发通知提出三项工作举措，目的是增加贫困地区农村学生上重点高校的规模，预计2014年贫困地区农村学生上重点高校的人数将比去年增 ...",
            "pic": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145859o663bevv3bx16x3z.jpeg",
            "dateline": "1 小时前",
            "ismp3": "http://demo.jizheweb.com/data/attachment/portal/201403/25/145903sjkvyzvi0fyk6m1i.mp3",
            "viewnum": 6032,
            "commentnum": "0",
            "favtimes": "0",
            "sharetimes": "0"
            }
            ];
            var element = $('#artist_list'),
            tpl = $('#t1').html();
            var html = _.template(tpl, datas);
            // 将解析后的内容填充到渲染元素
            element.html(html);